### ISSUE TITLE
Add support for Clear Region for Memcached

### ISSUE THREAD

**Issue by themakshter** [MichaCo/CacheManager#104]
Memcached does not support namespacing so we have to implement it ourselves. CacheManager does it via regions, but the ClearRegion method for memcached is not supported. 

A potential solution to this might be something suggested by [memcached team themselves](https://github.com/memcached/memcached/wiki/ProgrammingTricks#deleting-by-namespace) or [this approach](http://blog.cakemail.com/namespacing-in-memcached/).

**Comment by themakshter** [comment]
Creating this issue in case I work on it later.

**Comment by MichaCo** [comment]
Thanks @themakshter I will take a look at it soon :>

**Comment by MichaCo** [comment]
@themakshter hey, I finally had some time to look into this. I first didn't really liked the implementation as it leaves existing keys still in the cache and they might never be removed.

But hey, better than not having anything I guess ^^

I had to implement the solution slightly more complex than your approach and decided to do it from scratch instead of merging your PR, sorry about that. But thanks for pushing the idea 👍

**Comment by themakshter** [comment]
@MichaCo , that's perfectly fine, the PR was just a very basic solution, not meant to be added into the code - I had done that to get your thoughts on it. 

That doesn't matter much anyway, what matters is that you found and wrote a good solution to the problem :D

As for the items never being removed, that is unlikely to happen. Memcached uses LRU to determine what to remove from it, so if those keys are never used again, they will eventually get removed. [Link to memcached internals page](https://github.com/memcached/memcached/wiki/UserInternals)
