### ISSUE TITLE
Add support for AppFabric Caching

### ISSUE THREAD

**Issue by deadlydog** [MichaCo/CacheManager#107]
You already support a large number of caching providers (memcache, redis, etc.). One more great one would be [AppFabric Caching](https://en.wikipedia.org/wiki/AppFabric_Caching).

**Comment by MichaCo** [comment]
Hi @deadlydog thanks for the suggestion. I had support for AppFabric for some time.
The CacheManager package for AppFabric was not really heavily used and it was a ton of effort to test it because at least the locally installed version was horrible to configure and very unstable.

I dropped it because of that and because Microsoft officially ended working on that cache. They actually say that you should use Redis instead, and I totally agree with that. 

See https://en.wikipedia.org/wiki/AppFabric#History.

> In April 2015, Microsoft announced that it would end support for AppFabric for Windows Server on 2 April 2016

**Comment by deadlydog** [comment]
Yeah I just noticed too that it's going end of life this year, so I agree it's not worth the effort to add it back in. Thanks, I'll close this ticket.
