### ISSUE TITLE
Allow passing MemcachedClient for MemcachedHandle

### ISSUE THREAD

**Issue by themakshter** [MichaCo/CacheManager#118]
At the moment, the only way to pass in memcached settings for enyim is through adding these via the config settings. However, there may be circumstances where we might need to define our own `MemcachedClient` instance or something of the sort and set that in the CacheManager initiation. It would be nice to be able to pass in any object that implements `IMemcachedClientConfiguration`.

Adding [Enyim's wiki page](https://github.com/enyim/EnyimMemcached/wiki/MemcachedClient-Configuration) for reference

**Comment by MichaCo** [comment]
Sure, that makes sense, 
Will add it to my list ^^

**Comment by MichaCo** [comment]
Turned out I actually need the feature myself faster as expected to test the memcached hanlde, so, this will be in the next release ;)

**Comment by themakshter** [comment]
that's awesome! thank you very much!

**Comment by MichaCo** [comment]
Added the same option to redis, too. Now you can pass in an existing connection multiplexer.
/closing this one as it will be released soon

**Comment by themakshter** [comment]
Hey, just to check, does this mean you cannot now just pass in the enyim section like `WithMemcachedHandle("enyim.com/memcached")`?

**Comment by MichaCo** [comment]
@themakshter there is currently a bug in 0.9.3 unfortunately which causes that exception.
Actually it is a bug in the memcached client it seems, the ctor overload I'm using in that case doesn't initialize the client correctly.

The expected behavior is of course that it should also work with passing in the section name!

I reverted some changes back and it should work normal again in the next version.
Thanks for letting me know and sorry that I didn't catch it during testing ;)

**Comment by themakshter** [comment]
No problem at all, it's good to know it got fixed!
