### ISSUE TITLE
Not syncing from Redis to in-proc when adding new item

### ISSUE THREAD

**Issue by davenewza** [MichaCo/CacheManager#129]
I have two clients; one with an in-process cache and the other without, but both using the same distributed Redis instance as a backplane.

This is what I am trying to achieve:

![image](https://cloud.githubusercontent.com/assets/6212830/23059057/55afd948-f500-11e6-8e05-03d3d10db81a.png)

1. Client A adds a new item to the Redis handler
2. Client B's in-proc handler is synced with this new item
3. When Client B gets this item, it is retrieved straight from in-proc (and not from Redis)

But when Client B requests the item, it is still retrieved from Redis. 

**Client A configuration:**

```csharp
CacheManager = CacheFactory.Build<IAggregateRoot>(p => p
    .WithRedisConfiguration("redis", connectionString)
    .WithRedisBackplane("redis")
    .WithRedisCacheHandle("redis", true)
);
```
**Client B configuration:**

```csharp
CacheManager = CacheFactory.Build<IAggregateRoot>(p => p
    .WithSystemRuntimeCacheHandle("inprocess")
    .And
    .WithRedisConfiguration("redis", connectionString)
    .WithRedisBackplane("redis")
    .WithRedisCacheHandle("redis", true)
);
```

**How can I get Client B's in-proc cache synced when items are added to the Redis handler from Client A?**

**Comment by MichaCo** [comment]
Client B has to retrieve the item at least once from Redis, that's the only way for Client B to get the data. 
So, the first `Get` Client B is doing, will retrieve the item from Redis, every consecutive call eventually gets the item from the in-proc handle directly.
That's the expected behavior.

There is not really a reason for you to sync Client B's in-proc handle "preemptively" so to say, as Client B has to retrieve the item from Redis at some point anyways, right?

**Comment by davenewza** [comment]
Due to performance reasons, we need this specific cache to be prepopulated from the start.

So an item would only sync to Client B for an update or delete, but not for an add?

I hooked up some event logging on OnAdd and OnGet. I get the following:

> [Client A] ADD [MyKey] from Local
> [Client B] ADD [MyKey] from Remote
> [Client B] GET [MyKey] from Local

The first log occurs when the item is added to the cache by Client A. Client B adding from remote immediately logs afterwards.  The last log is Client's get call; why is this from Local? Surely it should be from Remote?

**Comment by MichaCo** [comment]
> So an item would only sync to Client B for an update or delete, but not for an add

Kind of, yes, on Update/Delete CacheManager tries to remove it from the in-proc handle(s) of other Clients connected to the same backplane channel, if the item exists, because the "source" changed.

CacheManager never transfers the actual cached data with change events through the backplane. That would cause massive performance issues and would be kinda pointless because the item is available in Redis anyways. 

> The last log is Client's get call; why is this from Local?

Because you did run the `Get` command locally to Client B. The `local` or `remote` flag is the origin the event came from. Get events do not get transported via backplane either; `Get` events will always be `local`.

In general, you already found that you can use the event system to preemptively populate your in-proc cache in Client B. 
If you really need that kind of functionality, it should work fine. I'm not doing that per default for good reasons.

Hope that makes sense ;)

**Comment by davenewza** [comment]
Yes, that makes sense.

So, all I would really need to do is configure the following event on Client B, This would populate the in-process cache when something is remotely added to the Redis cache.

```csharp
CacheManager.OnAdd += PropagateOnRemoteAdd;

private void PropagateOnRemoteAdd(object sender, CacheActionEventArgs e)
{
    if (e.Origin == CacheActionEventArgOrigin.Remote)
    {
        CacheManager.Get(e.Key, e.Region);
    }
}
```

**Comment by MichaCo** [comment]
Yup, that should work.

> CacheManager.Get(e.Key, e.Region);

I'd check if e.Region is null and then call the Get without region, otherwise you'll get an ArgumentNullException

**Comment by davenewza** [comment]
Right, yes. Thanks @MichaCo :)

**Comment by davenewza** [comment]
This also require's Client B to be configured with `CacheUpdateMode.Up`:

```csharp
CacheManager = CacheFactory.Build<IAggregateRoot>(p => p
    .WithSystemRuntimeCacheHandle("inproc")
    .And
    .WithRedisConfiguration("redis", connectionString)
    .WithRedisBackplane("redis")
    .WithUpdateMode(CacheUpdateMode.Up)
    .WithRedisCacheHandle("redis", true)
);
```

**Comment by MichaCo** [comment]
That should be the default value (if nothing is defined), but yes.
