### ISSUE TITLE
Problem with TryGetOrAdd in v1.0.0

### ISSUE THREAD

**Issue by sam-piper** [MichaCo/CacheManager#138]
Hi Micha,

I've just updated to v1.0.0, now I'm getting an issue with the TryGetOrAdd() method on the ICacheManager instance I'm using.

I'm using a system runtime cache handle with default expiration mode of Sliding and an item timeout of 30 minutes, and a Redis cache handle with same defaults, using a backplane. Here's my configuration code:

```
private ICacheManager<object> BuildCacheManager()
{
    var cache = CacheFactory.Build("CacheManager", settings =>
    {
        var serializerSettings = new JsonSerializerSettings { ObjectCreationHandling = ObjectCreationHandling.Replace, TypeNameHandling = TypeNameHandling.Auto };
        settings = settings.WithUpdateMode(CacheUpdateMode.Up)
                                .WithGzJsonSerializer(serializerSettings, serializerSettings);

        var part = settings.WithSystemRuntimeCacheHandle()
                            .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(30));

       BuildRedisConfiguration(part);       
    });

    return cache;
}

private void BuildRedisConfiguration(ConfigurationBuilderCacheHandlePart part)
{
    part.And
        .WithRedisConfiguration("RedisCache", config => config.WithAllowAdmin().WithDatabase(0).WithEndpoint("localhost", 6379))
        .WithMaxRetries(50)
        .WithRetryTimeout(100)
        .WithRedisBackplane("RedisCache")
        .WithRedisCacheHandle("RedisCache", true)
        .WithExpiration(ExpirationMode.Sliding), TimeSpan.FromMinutes(30));
}
```

The problem is that `TryGetOrAdd()` does not update the local cache handle anymore, whereas it was before. The Redis handle is updated correctly.

My expectation is that if the key doesn't exist and the value factory does not return null, then the result of the value factory should be added to all cache layers immediately, and the result returned via the out parameter of that method.

If I take out the Redis layer and just use the local layer then it works fine. It looks like the up-level synchronization from Redis -> Local is just not happening for this operation anymore.

Can you confirm that this is a bug and if there is a workaround or fix?

**Comment by MichaCo** [comment]
The behavior of `Add` changed, CacheManager doesn't add the cache item to all layers on `Add` anymore. This is intentional and not a bug.
The cached item will be added to all other layers the first time you do a `Get` instead.

So, what exactly is the problem you are facing?
`TryGetOrAdd` should still add the item only if it doesn't exist and otherwise just return it. Is that not the case?

**Comment by sam-piper** [comment]
Well my tests broke, so I needed to know whether this was a bug or intentional change, that's fine, I can adapt on my side.

Out of interest, why was this behavior changed for Add? Put still works the same as before, so not sure why Add and Put would work so differently now, given that they basically do the same thing? Correct me if I'm mistaken!

**Comment by MichaCo** [comment]
@sam-piper The reason for changing for Add was that, if you have multiple layers of cache handles, adding an item to both handles might have different results. 
Add should only add the item if it doesn't exist already, If the item exits in the first handle but not in the second for example, CacheManager would add it to the second one first and then fails on the second one...
It is hard to predict what might happen in all those scenarios, especially with distributed caches and concurrency in mind.

Adding the item only to the last handle and removing it from other layers prevents any inconsistency or ambiguity.

Put works fine because Put overrides any existing cached value anyways and doesn't care if it was there before or not.

Hope that makes sense

**Comment by sam-piper** [comment]
Yep that makes sense - thanks for the clarification.
