### ISSUE TITLE
CacheUpdateMode question and issues

### ISSUE THREAD

**Issue by bluefox** [MichaCo/CacheManager#15]
I'm not sure this is the intended behaviour for CacheUpdateMode.Full implementation.

The current implementation for BaseCacheManager - GetCacheItemInternal causes the cache item to be re-added to all the handles now this is fine and not noticeable if the handle is memory cache. However, re-adding any item to any other type of cache requires serialization of the item and replacing the item in the target cache. this overhead seems to defeat the purpose of the cache, especially when this is done every access of the item.

I'm not sure if there is any better way to implement this, but perhaps this should be implemented through the backplate notification instead?

**Comment by MichaCo** [comment]
Just use CacheUpdateMode.Up instead. 
`Up` doesn't put the item into each cache handle on Get. It does it only if necessary. 

I don't know if there is any real use case for the current "Full" update mode. I already thought about removing it. But maybe someone finds some use for it....

**Comment by bluefox** [comment]
Thanks for the suggestion, but I'm not sure Up is what I want either. Ideally, when I start a new app instance, it should fetch all the cached data already in distributed cache, then put those values in local memory cache. I guess this would be categorized as CacheUpdateMode.Down?

I think in most case, the update mode Up is already covered when a new item is added/updated it seems? (the code already adds new cache item to all handlers)

**Comment by bladefist** [comment]
I too was curious about this.  Put/Add updates things "above" but why does Get? And yes, if there is a 2nd instance, when it accesses a GET, if the local memory is empty, will it then check the redis, and then pull it down?

Thanks.

**Comment by MichaCo** [comment]
I think you are just to focused on the terms `Up` or `Down` ;) `UpdateMode.Up` does exactly what you described...

On cache `Get` the cache manager tries to retrieve the item from all handles in the list, and it case the item was found in the last handle for example, it will update all other cache handles in the list above the handle it found the item, which is why it is called `Up`.

So, if you have an in memory cache handle in front of a distributed one, and the item was found in the distributed cache, CacheManager will add it to the in memory cache. The next time you `Get` the same item, it will be retrieved from the in memory cache...

Hope this makes sense
