### ISSUE TITLE
Missing GetOrAdd overloads to work with CacheItem<T>

### ISSUE THREAD

**Issue by hobojoe** [MichaCo/CacheManager#152]
Hi,

Is there a way to perform a GetOrAdd while setting custom ExpirationMode and time (like with CacheItem)?

Thanks

**Comment by MichaCo** [comment]
Nope those overloads are missing.
I have that on my to-do list to add some of the missing overloads for those methods.

**Comment by hobojoe** [comment]
Ok,

I'll follow on this for when it gets implemented.

Thanks

**Comment by vijay8059** [comment]
Is this already available? Is see tag as Up for grabs but version setting as 1.2.0. In the releases section latest is 1.1.0.

**Comment by vijay8059** [comment]
And also looking at the commits , i am expecting some thing Like 
GetOradd(CacheItem ,Func<string, TCacheValue> valueFactory) something on this line. The overload that is committed is   public TCacheValue GetOrAdd(CacheItem<TCacheValue> item)
       {
          NotNull(item, nameof(item));
       return GetOrAddInternal(item);
       }

**Comment by MichaCo** [comment]
@vijay8059 Regarding your first question, you answered it yourself. Regarding the other question, I think the addition will do exactly what you need, your code example doesn't make any sense though.

**Comment by MichaCo** [comment]
@ahockersten Thanks again for the PR! It will be in the next release ;)

**Comment by hobojoe** [comment]
I tried using this new overload without success:

![1](https://user-images.githubusercontent.com/1886514/34408621-3ffc0c0e-ebac-11e7-9a8c-eff51e00a526.png)

Not sure if I'm using it incorrectly, but i noticed that when using this overload it stores a CacheItem into the cache, and not my TestClass object. I also isn't updating the expiration of the item.

Am I doing something wrong?

Thanks

**Comment by MichaCo** [comment]
@hobojoe thanks for reporting this.
This is actually an odd behavior where the code executes the wrong overload and indeed caches a `CacheItem<T>` instead of the value by mistake.

The problem here is the generic type of the CacheManager instance, which is `object`. In this scenario, the two generic overloads...
```
TCacheValue GetOrAdd(string key, Func<string, TCacheValue> valueFactory);

and

CacheItem<TCacheValue> GetOrAdd(string key, Func<string, CacheItem<TCacheValue>> valueFactory);
```
...are ambiguous **if `T` is not `object`**, and the first one will be used, even if you return `CacheItem<T>` from the factory `Func`.

According to the API premise, the first call to `cache.GetOrAdd` should return a `CacheItem<object>` and not the value. Meaning, your cast should have failed in that line already. The second time, it returns a `CacheItem<TestClass>` because that's what is now cached on that `key`, which is also not really "friendly".

Your "mistake" here is, that you return `CacheItem<TestClass>` from the factory methods. `T` is `object` in your case, which means you should return `CacheItem<object>` instead. That's not really easy to spot and with the current API there is no compile time check preventing you from doing it wrong. I will have a look into improving that...

You can also make your CacheManager instance of type `TestClass` to get a 100% clear understanding of what the API is supposed to do.
Or, use the TryGetOrAdd overloads which are a little bit more explicit for the return types (out param).

---

I will take a look at what the best options are to fix this behavior. It is not really a bug because it will work if used correctly. But because of the ambiguity in the "T = object" scenario the API seems really user unfriendly ;)

One option would be to rename the `CachItem<T>` overloads to `GetOrAddCacheItem`.

I might also add a type check to prevent caching `CacheItem`s
