### ISSUE TITLE
CacheActionEventArgs contains key and origin as string. 

### ISSUE THREAD

**Issue by vijay8059** [MichaCo/CacheManager#153]
Hi ,
I am using this overload to addorupdate a cache.
        TCacheValue AddOrUpdate(CacheItem<TCacheValue> addItem, Func<TCacheValue, TCacheValue> updateValue);
So my key here is of type CacheItem
 when the OnAdd/Update event gets raised but in the CacheActionEventArgs i am receiving the key and region as string. expecting of type CacheItem.

**Comment by MichaCo** [comment]
I think your misunderstand what CacheItem actually does and how that stuff is working. What you describe is the expected behavior.

CacheItem<T> is not the key you are adding. CacheItem is a wrapper around `key`, optional `region` the `value` and expiration settings. 

In general, there is no difference in using either the overloads utilizing CacheItem<T> or passing in the key as string + value etc... Internally, it does the same thing, storing a value on the defined key. CacheItem can be used to set a expiration mode/time per cached value. That's all you can actually use it for.

That's why you get key/region in the event, hope that's clear enough.
