### ISSUE TITLE
Memory Cache instance key

### ISSUE THREAD

**Issue by efredin** [MichaCo/CacheManager#16]
The MemoryCacheHandle<T>.instanceKey field makes working with memory caches a bit painful.  This essentially forces you to scope any memory cache instances as singletons.  This becomes even more difficult when working with different typed caches. Is this scoping intentional?  A workaround for multi-threading or multi-worker-process application pools maybe?

For example:

```c#
var cacheA = CacheFactory.FromConfiguration<string>("myConfig");
cacheA.Add("key", "value");

var cacheB = CacheFactory.FromConfiguration<string>("myConfig");
cacheB.Get("key"); // returns null

**Comment by MichaCo** [comment]
Great question. 
The reason is that `MemoryCache` is basically static, too.
Which means, if I create two `MemoryCacheHandle`s, both using `System.Runtime.Caching.MemoryCache.Default`, and I call clear on one handle, it would clear the whole cache (both handles). Which could cause very bad results.

More importantly, if I have two CacheManager instances for two different types for example, and both are using the same `MemoryCache` configuration, we could run into cache key conflicts...
That's why I have to prefix all keys for one CacheHandle instance. Also, to clear all keys from that instance only, I have a dependency cache entry for that instance where all cache items are getting linked to...

So, yes, there are many reasons to have that instance key ;)

Back to your concern that this forces you to scope CacheManager instances as singleton: 
Yes, and it is not a bad thing. You should always use the same instance across you whole application and have it as singleton somewhere!
That's because instantiating CacheManager can be expensive. Depending on the handles you have. configured, cache handles might have to connect to a server or do other stuff when instantiated...

Hope that clarifies all that a little bit ;)

**Comment by efredin** [comment]
This is a really good explanation.  Thanks for sharing.
