### ISSUE TITLE
LRU + max size eviction policy

### ISSUE THREAD

**Issue by gigi81** [MichaCo/CacheManager#188]
Hi,
I was wondering if there is any way to achieve the following.
I would like to set a limit of size for the cache (like count of items or even better heap size like 512MB of memory). When the cache is full I would like the cache to automatically evict the items in a least recently used (LRU) fashion.
Is this a supported scenario? I couldn't find any info on this so I guess it is not.
If it is not, I might consider implementing this myself, but of course I would appreciate any insights from maintainers in terms of how they would tackle this within the existing code base. And of course if they would be willing to review/merge a PR that implements such a feature.
Thanks
Luigi

**Comment by MichaCo** [comment]
That is not something CacheManager will implement because it is up to the cache vendor. 
If you use Redis, it has all of that configurable.
For System.Runtime.Caching, that one also has an implementation of memory pressure.
Microsoft.Extensions.Caching had another implementation of memory pressure in 1.x. That feature was removed though in 2.0 because it is not really working well I guess.

In general, in managed code, you cannot really tell how large an object or list of objects is because of many reasons.
That's why you'll not very likely get that feature in many in-memory caches in .NET

Hope that helps

**Comment by gigi81** [comment]
Hi @MichaCo 
Thanks for your quick reply. That was definitely helpful.
I understand the reason this cannot be a feature of the core library.

I'm currently using the System.Runtime.Caching so I will have a look into the configuration for that and see if it actually works as I'm expecting. If not I guess it will be a bug report for someone else :-)

I will close the ticket but, if I manage to make it work, I will update the ticket with an example configuration, in case someone else stumbles into this.

Thanks
Luigi

**Comment by MichaCo** [comment]
Just FYI, for System.Runtime.Caching this can be configured right now only via web/app.config.
There is a ticket open to add that to the configuration builder of CacheManager, see https://github.com/MichaCo/CacheManager/issues/177
