### ISSUE TITLE
Add Exception event to BaseCacheManager

### ISSUE THREAD

**Issue by themakshter** [MichaCo/CacheManager#206]
A solution you suggested for handling distributed cache errors was to switch it out with an in-memory cache ([source](http://michaco.net/blog/WhatIfRedisStopsWorkingHowDoIkeepMyAppRunning)). In this particular case, the Redis client has its own events which are able to inform us when connection fails and when it doesn't. This may not exist for other solutions (e.g. Memcached) and we need a way to figure out if the distributed cache nodes are down or not. One solution I can think of is to have an ExceptionThrown event which passes along the exception message. If this occurs, we can check the message to see if the problem is related to node connection and hence switch to in-memory caching and retrying after 30 mins. 

What do you think? I am interested if you have another suggestion in mind for other cases.

**Comment by MichaCo** [comment]
Hey @themakshter, thanks for the question!
First of all, I'm **not** suggesting to switch to in-memory when Redis is unavailable. I only explored it as an option to showcase the issues with such a solution. I would never suggest to do that unless you are 100% aware of the issues and your app doesn't have a problem with it.

Regarding events in case of exceptions, I'm not a big fan of that because you already have exceptions, just try/catch...
You could just set retries to 0 and catch any exception yourself and decide what to do with it ;)

Though, maybe it is a good idea to be able to hook into the retry mechanic of CacheManager to have more control over what should be retried... Basically an event on handled exceptions, would be a callback Func though, returning a bool or something...
All unhandled (by CacheManager) exceptions will bubble up as normal anyways, I don't see a reason to add another event for that. 

If you still want to get an event for redis nodes or connection or configuration changes, this can already be done by using the StackExchange.Redis client directly. The client provides some of those events... 
You can instantiate a new `ConnectionMultiplexer`, add your event listeners and then pass it to CacheManager instead of having CacheManager create a new `ConnectionMultiplexer`.

**Comment by themakshter** [comment]
Thank you for your reply and input!

Yes, I understand. I thought your suggestion was a good idea because that solution has been previously been implemented in our infrastructure too and it makes lots of sense to ensure that the performance doesn't suffer too much.

It also makes sense that you wouldn't want to add this functionality to the CacheManager generally - I can probably just extend the `BaseCacheManager` now that it is unsealed and use it for my own needs. But in a solution where you have a `CacheKeeper` sort of class, since you are not wrapping the get, set, remove methods, it is difficult to communicate exceptions or errors in the cache which is returned to the user as this class only returns a `CacheManager` instance and the user is free to call any functions they want on it. If you wrap all the methods inside the `CacheKeeper` class, then you can catch exceptions yourself and switch the instances between distributed and in-memory. But then you lose the rich functionality which `CacheManager` provides.

For Redis, the events exist, as showcased in your example. But not every distributed cache client has one. In my particular case (memcached), there doesn't exist one and the only thing I can think of is regularly connecting to the server and check if it is running, but that seems a horrible way of doing it.

**Comment by MichaCo** [comment]
/closing this for now. There is no easy "fix" for what you are trying to do and yeah, memcached is pretty limited in what the server has to offer. 
Not sure either what the best way is to check uptime. There are solutions out there which wrap memcached on the server side and add additional functionality to make it robust though.
