### ISSUE TITLE
Redis.StrongName reference

### ISSUE THREAD

**Issue by nebelx** [MichaCo/CacheManager#208]
accorrding to this post [(https://github.com/imperugo/StackExchange.Redis.Extensions/issues/30] StackExchange.Redis.StrongName is deprecated. Isn't it reasonable to switch dependency to StackExchange.Redis ? 
This dependecy causes realy much problems, beacause StackExchange.Redis.Extensions.* has reference to not stronglynamed assembly, so there is no way to use Cachemanager.StackExchange.Redis with other StackExchange.Redis.Extensions without hacks.

**Comment by MichaCo** [comment]
The [StackExchange.Redis.StrongName](https://www.nuget.org/packages/StackExchange.Redis.StrongName/) package is totally not deprecated at all. 
Not sure why it would a problem for another library to just public sign it. There is no downside for apps which are not signed to just use it... On the other end, if you build an app and have to sign it, you cannot use unsigned packages. That's why I changed it for CacheManager a while ago and why many other packages are signed per default (like all aspnet/dotnet core package). 
I'm also not sure why StackExchange.Redis still has those 2 variants as different packages in the first place ^^

:tldr: no I will/can not change that

**Comment by nebelx** [comment]
Than from quick reply, 
I did not noticed that CacheManager is stronglynamed itself, so of course it's not possible.
I also do not have idea why  StackExchange.Redis keeps both versions of packages.
