### ISSUE TITLE
question: will cachemanager suport json when cached by redis?

### ISSUE THREAD

**Issue by capqueen** [MichaCo/CacheManager#21]
I'm changing my cache module to cachemanager, but find some problems. 
my old redis cache use json serialize, but cachemanager use binary. 
is there any way to change the serialize mode in cachemanager?

**Comment by MichaCo** [comment]
at the moment no, not directly, because it is not very "safe" to serialize and deserialize with Json from any kind of object. There can be pitfalls.
That being said, you can create a string based cache manager instance and serialize it yourself. This will totally work.

This might change in the future though.
