### ISSUE TITLE
CacheItem.WithExpiration() disappeared

### ISSUE THREAD

**Issue by memark** [MichaCo/CacheManager#210]
It seems the `public` method `CacheItem<T>.WithExpiration()` was made `internal` (a breaking change!) in version 0.9.3 without being mentioned in the release notes. The relevant commit is https://github.com/MichaCo/CacheManager/commit/9aa86cf1a2a6db6cdbb4fe24389a3b81a4b2491f

This change is currently stopping us from upgrading smoothlessly beyond 0.9.2.
I want to check if this was a deliberate change?
Would you consider making it `public` again? Given that the `ExpirationMode` enum still exists, it seems reasonable to me to continue to be able to use it to specify the expiration mode for a cache item.

**Comment by MichaCo** [comment]
Hi @memark, yes that was done for some reasons ;)
There are methods for the different expiration options available though: `WithAbsoluteExpiration` and `WithSlidingExpiration` and `WithNoExpiration`, which all overrule the default per-handle expiration settings.
Then there is a new `WithDefaultExpiration`, which can be used to reset a custom expiration back to the per-handle configure one.
All that is implemented with a new enum value `Default`. 
I also had to introduce a flag `UsesHandleDefault` which gets persisted with the cache item to reason about what should happen if the item gets added to the cache.

All that is very internal only and the user shouldn't worry about what those things mean. That's why I made the general `WithExpiration` method internal and have you use the more explicit methods.

If you have a use case where you absolutely need the general method, let me know. But I think the API provides enough alternatives.
Sorry for breaking your upgrade though ;)

**Comment by memark** [comment]
Hi @MichaCo and thanks for the explanation!

I would not say I have a strong use case. It's more of a nuisance that our code is sprinkled with calls to `WithExpiration()` (where the enum value is being passed in from somewhere else).

I suppose I can get by by introducing my own method, switching on the enum value and then calling the appropriate method. It's just a little less smooth and less invasive than I was hoping the upgrade would be.
