### ISSUE TITLE
Expiration not working with multiple layers

### ISSUE THREAD

**Issue by hobojoe** [MichaCo/CacheManager#213]
I tried working with multiple layers using expiration and I don't seem to get it working properly

Here is my code:
```
var cache = CacheFactory.Build(p => p
                // Only retry 5 times.
                .WithMaxRetries(5)
                // The in-process cache will serve aggregates straight from memory.
                .WithSystemRuntimeCacheHandle("in-process")

                .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))

                // Add the backplane Redis cache handle to establish a multi-layer cache.
                .And
                // Distributed cache (Redis).
                .WithRedisConfiguration("redis", $"localhost:6379,abortConnect=False")
                // Set as backplane to synchronise from the other clients.
                .WithRedisBackplane("redis")
                // CacheUpdateMode.Up will synchronise the in-process cache from additions to Redis.
                .WithUpdateMode(CacheUpdateMode.Up)
                // Use this backplane cache handle.
                .WithRedisCacheHandle("redis", true)
                .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromSeconds(5))
            );
            
            string cacheKey = "teste-key";

            cache.Add(cacheKey, "1");

            // Wait 4 Seconds
            System.Threading.Thread.Sleep(4000);

            var val = cache.GetOrAdd(cacheKey, (v) =>
            {
                Console.WriteLine("Wrote in cache");
                return "2";
            });

            Console.WriteLine(val); // Prints "1" as expected (expiration is 5 seconds)
            // Wait 4 Seconds
            System.Threading.Thread.Sleep(4000);

            val = cache.GetOrAdd(cacheKey, (v) =>
            {
                Console.WriteLine("Wrote in cache");
                return "3";
            });

            Console.WriteLine(val); // Prints "1" instead of "3". It should have already expired as it's been 8 seconds since it was added
```
I am not sure if my config is incorrect or anything. If I only work with 1 layer it works fine, whether it is Redis on InMemory.

Thanks in advance!

**Comment by MichaCo** [comment]
Hi @hobojoe, this is actually working correctly. Just not really easy to explain but I'll try ;)

You are using `.Add` to cache the item, `Add` only adds the key to the lowest level (2nd level = redis in your case).
After 4 seconds you do a `Get`. Get with `UpdateMode.UP` will now add the item to the first cache layer. The configured expiration here is also 5 seconds. 
The second GetOrAdd after another 4 seconds will now find the cached item in the first layer. The second layer doesn't have the cached item anymore though.

The behavior of CacheManager is correct. That being said, you should probably not use the same expiration for both layers. The most common use case would be a much shorter in-memory lifetime then the Redis layer, so that you do not run into those scenarios where you have eventually stale data in memory.

Another option would be to enable keyspace notifications on the Redis layer. If configured properly on the server and in CacheManager (`WithRedisConfiguration("redis", $"localhost:6379,abortConnect=False", enableKeyspaceNotifications: true)`), eviction events from Redis will also remove the item from the in-memory layer.
Keep in mind, those events might not get triggered immediately and your test case might still fail from time to time because of timing issues... Those things are pretty hard to test reliably. 

To help understand what is going on within CacheManager, you can add `Trace` logging to and inspect the log messages:
To do so, add `CacheManager.Microsoft.Extensions.Logging` and `Microsoft.Extensions.Logging.Console` Nugets and the following code to initialize the logger factory:
```
var loggerFactory = new LoggerFactory().AddConsole(LogLevel.Trace);

var cache = CacheFactory.Build(p => p
      .WithMicrosoftLogging(loggerFactory)
      ...
```

**Comment by hobojoe** [comment]
Got it!

Just one question though, my idea is to use the InMemory cache first, and Redis to be the last option (mainly for synchronization with other servers).

I thought that my config was doing that instead of using Redis first. What should I change to work the way I expect?

Thanks

**Comment by MichaCo** [comment]
It will use in-memory "first" after the key has been added to that in-memory layer. You don't have to change anything.
But, to "sync with other servers" as you say, the key must exist in Redis. That Redis layer is basically the "master" in your cache. That's why the key gets stored there first.
There are other reasons why `Add` only adds it to Redis first and only a `Get` stores it in-memory. The key could already exist in Redis for example...

**Comment by hobojoe** [comment]
Great, thanks!
