### ISSUE TITLE
why not support local memory cache with BackPlate

### ISSUE THREAD

**Issue by capqueen** [MichaCo/CacheManager#22]
I found that while I config WithSystemRuntimeCacheHandle with RedisBackPlate,it not work.
Then I found code in RegisterCacheBackPlate do not add handler which configed as  IsBackPlateSource.
```
if (!handle.Configuration.IsBackPlateSource)
 {
           handleList.Add(handle);
 }
```

Can I modify it to support BackPlate when only local memory cache be configed?

Is it right just add the handler to handleList,then the item in memory will be removed?

**Comment by MichaCo** [comment]
I'm not really sure what problem you are trying to solve. 

The back plate concept is meant to keep a local 1st-level in-memory cache in sync if you have a distributed cache, like Redis, running as 2nd level cache AND you have multiple instances of your app running in parallel. 
The back-plate keeps your local 1st level cache in sync if another instance e.g. removes a cache entry, so that you do not work with possibly invalid data.

Why would you do that if you have in memory cache only?

Maybe describe what you are trying to do and I might be able to help you out ;)

By the way, those kind questions should better be asked on stackoverflow.com.

**Comment by capqueen** [comment]
I'm sorry about that. I'll ask on stackoverflow next time. I just want to save some item in memory like units(USD\RMB\...) ...  I think there is no need to save them to redis, but I want keep sync. this is my question

**Comment by MichaCo** [comment]
no worries ;)

You want to keep that in sync with what?
