### ISSUE TITLE
StackExchange.Redis Handle Timeout

### ISSUE THREAD

**Issue by jcorrea-origin** [MichaCo/CacheManager#234]
in my code i had  a try catch 

![getitem](https://user-images.githubusercontent.com/13002228/40079943-de3ca480-585f-11e8-9214-5cc6a60f56e8.JPG)

I need to manage this error and try to use database.

StackExchange.Redis.RedisTimeoutException: Timeout performing PUBLISH CacheManagerBackplane, inst: 1, mgr: ExecuteSelect, err: never, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: TORRES-WEB, serverEndpoint: Unspecified/xmlOurRedisCalls.redis.cache.windows.net:6379, IOCP: (Busy=1,Free=999,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisSubscriber.Publish(RedisChannel channel, RedisValue message, CommandFlags flags)
   at CacheManager.Redis.RedisCacheBackplane.Publish(Byte[] message)
   at CacheManager.Redis.RedisCacheBackplane.<>c__DisplayClass20_0.<<SendMessages>b__0>d.MoveNext()

**Comment by MichaCo** [comment]
I don't really understand what you question is. Can you explain?

And also, what version of CacheManager are you using? The newer version should do all Backplane things asynchronously. You might see timeout errors in the logs but not directly in a call.

**Comment by jcorrea-origin** [comment]
my question is , if the redis server is timeout i need to use my database to extract the information.
 
 i am using 

CacheManager.StackExchange.Redis 1.1.2.0
CacheManager.Core 1.1.2.0
CacheManager.SystemRuntimeCaching 1.1.2.0

so, i need to handle a timeout error.

**Comment by MichaCo** [comment]
Yeah you might have to handle exceptions if you want to react on it if your Redis Server behaves strange.
CacheManager has also build in retries which you can try to use/test with.

I'm really not sure why you get a Timeout Exception from the backplane though. That stacktrace should never bubble up to user code as it is within another task running asynchronously to your code?! I'm confused.
But yeah, in general, if you don't want to use retries and go to the database if Redis doesn't work, you have to try/catch I guess

**Comment by MichaCo** [comment]
Yes, you can play with those settings and test your application. Again, I cannot really do anything about timeouts as that's a thing handled by the StackExchange client. There are many issues related to that on the StackExchange.Redis GitHub repository. But that's just how the client works.

Again, you can specify retries and retry timeout between retries in CacheManager. Timeouts will be retried because it usually means the server is just busy and we can try again a little bit later...

If you want to implement a more relaxed retry with back off timeouts, you can do that with a simple loop and try catch and e.g. `await Task.Delay(timeout * runs +1)` to reduce pressure on the server
