### ISSUE TITLE
How to the CacheFactory support generic instance?

### ISSUE THREAD

**Issue by 18098924759** [MichaCo/CacheManager#27]
It is not convenient for each type to be registered.
In addition, do not support connection retry,For example, when the redis server is down to restart, the client should be able to reconnect to the server when requested

**Comment by MichaCo** [comment]
What do you exactly mean with "support generic instance"? 
If you don't want to configure each type, use "object". there are overloads everywhere to create non typed instances...
If you want to use DI to inject an instance per type, see https://github.com/MichaCo/CacheManager/issues/20

Cachemanager actually handles retries for you if you use Redis. you can controll the connection timeout in the redis configuration and the cache manager itself has properties for retry timeout and max retries. 
That being said, do you have a reproduceable configuration/scenario you are using where this is not working? Please post it here so that I can test it.
Thanks

**Comment by 18098924759** [comment]
I'm use autofac,but I don't know how to register an instance in bulk,Can you provide an example for me,thank you !

Here is my code:
//var intCache = CacheFactory.FromConfiguration<int>("intCache", cfg);
//var stringCache = CacheFactory.FromConfiguration<string>("stringCache", cfg);
//var objectCache = CacheFactory.FromConfiguration<object>("objectCache", cfg);
            
 //builder.RegisterInstance(intCache);
  //builder.RegisterInstance(stringCache);
  //builder.RegisterInstance(objectCache);
   //builder.RegisterInstance(cache);


  var container = builder.Build();
  DependencyResolver.SetResolver(new AutofacDependencyResolver(container));

**Comment by MichaCo** [comment]
Well, autofac also has a way to register open generics, something like this should work

    var cacheConfig = ConfigurationBuilder.BuildConfiguration(...);

    var builder = new ContainerBuilder();
    builder
        .RegisterGeneric(typeof(BaseCacheManager<>))
        .WithParameters(new[] 
        {
            new TypedParameter(typeof(string), "myCache"),
            new TypedParameter(typeof(CacheManagerConfiguration), cacheConfig)
        })
        .As(typeof(ICacheManager<>))
        .SingleInstance();

Don't forget the `SingleInstance()` call to make each cache manager instance the container creates, a singleton.

**Comment by jrt324** [comment]
In version 0.9.3 should be:

`            builder.RegisterGeneric(typeof(BaseCacheManager<>))
                .WithParameters(new[]
                {
                    new TypedParameter(typeof(ICacheManagerConfiguration), cacheConfig)
                })
                .As(typeof(ICacheManager<>))
                .SingleInstance(); `
