### ISSUE TITLE
Failed to connect to sentinel

### ISSUE THREAD

**Issue by arrkaye** [MichaCo/CacheManager#285]
Hi, 

We currently connect to Redis just fine on port 6379. However, we recently upgraded our instance to use the stable/redis-ha Helm chart and this comes with a Sentinel installation.

I changed our connection string to connect to it on port 26379, but it just fails to connect.

I thought it was supported now that Sentinel support is in the SE client library?

Thanks.

**Comment by MichaCo** [comment]
As far as I know the sentinel support PR in Stackexchange.Redis is still not merged.
There is some basic support though for sentinel setups. 
I did some testing with that a couple of years ago and nothing really changed so that should still work.
I bet you had only the sentinel configured an no other servers, or you have other network issues which prevents the connection.
Anyways, that shouldn't have anything to do with this library.
