### ISSUE TITLE
Basic problem with .NET Standard....

### ISSUE THREAD

**Issue by natiki** [MichaCo/CacheManager#288]
Hi,

I am following http://blog.chudinov.net/my-cache-interface-and-implementations/ but want to put this into a .NET Standard library. So I create a .NET Standard 2.0 class library:

![image](https://user-images.githubusercontent.com/4738140/66282317-9fb69a80-e90a-11e9-9574-9da1c197616e.png)

and then took the code from https://github.com/mchudinov/CacheNet. But when I compile it I get the following error:

![image](https://user-images.githubusercontent.com/4738140/66282382-e86e5380-e90a-11e9-91c9-5a99bdedef9d.png)

with the following package versions:

![image](https://user-images.githubusercontent.com/4738140/66282433-1c497900-e90b-11e9-8129-37da86746d8c.png)

For the life of me I cannot figure out how to create the ICacheManagerConfiguration such that it reads the settings from web.config.

Can you please point me in the right direction?

**Comment by MichaCo** [comment]
I'm not the owner of that blog or github repo and the code samples, I guess you should ask there.

But anyways, the solution there uses the old csproj system and the full .NET framework. 
It also uses ConfigurationManager, and the old xml based configuration system. 
That doesn't exist in netstandard2.0.

CacheManager <=1.2.0 doesn't support that way of configuration with netstandard, that's why that overload in CacheFactory doesn't exist for you.

Support for that will come back in CacheManager 2.0 or so because MS added support back with the `System.Configuration.ConfigurationManager` nuget package.

**Comment by natiki** [comment]
Hi @MichaCo, 

I appreciate you are not the owner of that blog just gave it for context.... 

1. When do you think CM 2.0 will be RTM? I have been tracking https://github.com/MichaCo/CacheManager/issues/221
2. Assuming a .NET Standard library that contains CM what is the "correct" way with CM 1.20 to load from a JSON configuration?
