### ISSUE TITLE
Possibility to use shared CacheManager instance in CacheManagerOutputCacheProvider and in MVC application?

### ISSUE THREAD

**Issue by tatarincev** [MichaCo/CacheManager#32]
Hi @MichaCo thanks for great caching impl but we have some problem.

In our application we used  full page caching throught using *OutputCacheAttribute* (integration by *CacheManager.Web*)  and use *ICachingManager* in application code. 

And we have problem with invalidation (clearing) cache because in code we have different instance *ICachingManager* not such that used in *CacheManagerOutputCacheProvider*. 
Can you suggest how to clear cache in both cache providers instances or how to share one *CacheProvider* instance between *CacheManagerOutputCacheProvider* and application code.

Thanks.

**Comment by MichaCo** [comment]
Hi @tatarincev 
Yeah the output cache thing is a little bit tricky because you cannot really inject anything into the initialization of that thing.

To access the actual cache manager instance, there is a static property on `CacheManagerOutputCacheProvider.Cache`.

You should be able to control everything you need through that.

**Comment by tatarincev** [comment]
Thanks I think this solution is suitable.
