### ISSUE TITLE
Difference between Microsoft.Extension.Caching.* packages

### ISSUE THREAD

**Issue by bugproof** [MichaCo/CacheManager#326]
What advantages does it have over using e.g. Microsoft.Extensions.Caching.StackExchangeRedis and official `IDistributedCache` and `IMemoryCache` abstractions?

Some of the disadvantages I see is less control, e.g. forced serialization library https://github.com/MichaCo/CacheManager/issues/278

**Comment by MichaCo** [comment]
IDistributedCache doesn't have any features other than saving a byte array as far as I know. 
That's pretty much doing nothing and cannot really be compared to CacheManager. 
That being said, if you don't need any of the CacheManager specific features and just want to quickly throw your byte arrays into Redis then just use those simple abstractions!

What do you mean with forced serialization? CacheManager has many different serialization implementations which should work for most cases so that you as the user don't have to care about that. That being said, you always have the option to not use a build in serializer and also just cache a byte array and care about serialization somewhere yourself.
