### ISSUE TITLE
Enhancement: overload of Put that works like Update

### ISSUE THREAD

**Issue by christianacca** [MichaCo/CacheManager#4]
Hi Michael,

I like the idea of Update resolving conflicts. So much so I think it would make sense if there was an overload of the `Put` method that works in the same way.

This new `Put` method would take a parameter named `addOrUpdate` of type `Func<TCacheValue, TCacheValue>`

On calling this `Put` method, if the `key` was not found then the first argument supplied to this delegate would be `null` (well actually `default(T)`). If on the other hand the `key` was found, its associated value would be supplied.

The `Put` method would then continue to execute the `addOrUpdate` delegate until conflicts were resolved.

Do you think this is a good idea or am I missing something fundamental?

Thanks
Christian

**Comment by MichaCo** [comment]
I like the idea, problem is that I'd have to null check inside the lambda which is not really what I want to force someone to do. You'd have to check if the value is null => create a new one, otherwise, update existing...

What about two Funcs one for add one for update and CacheManager decides which one gets invoked depending on the cache key has been added already or not?

Could be `Put(string key, Action<TCacheValue> onAdd, Func<TCacheValue, TCacheValue> onUpdate)` or something like that...

**Comment by christianacca** [comment]
Perfect.

What you're suggesting matches the signature of AddOrUpdate implemented by
ConcurrentDictionary

C

**Comment by MichaCo** [comment]
Just added the functionality. There is now `AddOrUpdate` on `ICacheManager`.

Also, `Update` has received some refactoring, the `Update` method now returns the value updated or null if the update failed (was bool).
There is a new method `TryUpdate` which returns bool and has an `out` param for the value.
Did that because `AddOrUpdate` also returns the value added or updated (which is somehow needed if you use that) and to be more consistent.

Let me know what you think ;)

**Comment by christianacca** [comment]
Cool thanks for that. I'm going to start using it in the week...
