### ISSUE TITLE
How about Contains / Exists implementation for a key?

### ISSUE THREAD

**Issue by keerthivasanm** [MichaCo/CacheManager#46]
It really helps if the value is a huge payload.

**Comment by MichaCo** [comment]
Yup, sounds like a potential improvement

**Comment by killergege** [comment]
I'm a bit surprised that this is missing, it's a basic feature for a cache manager !
How do you know that the value returned by Get<T> is a cached value or a default value because the key doesn't exist ?
To me it sounds dangerous to return a value if the key doesn't exist...

**Comment by MichaCo** [comment]
@killergege That's the normal behavior of caches. If the key doesn't exist, you cannot return anything. And CacheManager returns default(TCacheValue) which is null for value types etc...

The only other option would be throwing a not found exception, which would cause all kinds of other oddness because then you'd have to try/catch every cache call... Which is even worse than a null check...

That being said, a TryGet and/or Exists method will be helpful for non value types.
Although, you can always use the `GetCacheItem` method which will always return null if a key doesn't exist, independent of the `TCacheValue`

**Comment by jzabroski** [comment]
Agreed with MichaC. Null is a meaningless value. If you want a way to reify
a null, create a Maybe wrapper type. There are many projects on github
which provide not only Maybe but Option type as well  (to denote optional
parameters/values).

**Comment by sam-piper** [comment]
+1 - we would really like this feature too. We have cache loading algorithms that we want to transfer from a previous caching implementation that need to test for the existence of keys without transferring any values from the Redis layer, otherwise performance suffers.

For now I'll have to plug this gap manually, would be great to have official support in the CacheManager API.

**Comment by MichaCo** [comment]
@sam-piper @keerthivasanm 
 Sorry that it took so long but it's finally implemented and will be in the next release.
