### ISSUE TITLE
Twemproxy support

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#54]
I am trying to add twemproxy support for the library but I have hit a wall because the Servers API from StackExchange.Redis is not available if the proxy option is on and CacheManager relies heavily on this API for example to detect the features available in the particular endpoint (lua, etc..). Also the pub/sub feature of Redis is not supported so the backplane cannot be set :(

**Comment by TMiNus** [comment]
A crazy idea, can we make the BlackPlane feature open to customs pub/sub back-ends like we do with the Serializer or the Logger.

**Comment by MichaCo** [comment]
> A crazy idea, can we make the BlackPlane feature open to customs pub/sub back-ends like we do with the Serializer or the Logger

It is already, since the beginning. BaseBackplane is in Core

**Comment by MichaCo** [comment]
Regarding twemproxy support. I guess in most cases where APIs are not available, the features using those APIs must be disabled and/or fall back to defaults if possible, if proxy is enabled. 

Should be possible to identify through the redis configuration proxy type?

**Comment by TMiNus** [comment]
Well actually StackExchange.Redis just support Twemproxy so either you have that one or you don't have one at all

**Comment by TMiNus** [comment]
Any gotchas in the implementation of a different pub sub system for this library?

**Comment by MichaCo** [comment]
> Well actually StackExchange.Redis just support Twemproxy so either you have that one or you don't have one at all

I know, just saying, CacheManager would have to disable certain features if proxy is enabled and not try to identify features and such. Not planning to implement that soon though.

> Any gotchas in the implementation of a different pub sub system for CacheManager

Just look at the redis based implementation, it is pretty straight forward. Depends on the system you are using and how you want to serialize the messages I guess

**Comment by MichaCo** [comment]
Finally working on adding support for Twemproxy in 1.0.2.
As far as I can tell right now, the following features will simply be not working if Twemproxy is used:
* Redis backplane
* Clear command (as Flush is not supported)
* Lua scripting (as there is no way to publish Lua scripts to all servers in the beginning)
  * The redis handle will fall back to version 2.4 support mode and does all commands without Lua
* Any `Update` calls will throw an exception and are not supported
  * The implementation without Lua uses `CreateTransaction` from stackexchange.redis which does a `MULTI` which is not supported on Twemproxy...

It will be pretty limited, but hey, at least it kinda works then ;)

**Comment by MichaCo** [comment]
@TMiNus 
In https://github.com/MichaCo/CacheManager/commit/07f1db9ff29291accb76c7b1bbb731d49bff6091 I added Twemproxy support, maybe you could give that a try and test it with the beta packages (1.0.2-beta-1510+).

The following things are not working because it is not supported in that mode:
* Redis Backplane and keyspace events (as Pub/Sub is not supported with Twemproxy)
* Clear and Count (as Twemproxy doesn't let me access the servers list)

Lua scripting works, I had to add a switch though, to disable preloading of the lua scripts. In Twemproxymode, the lua will be passed along with any EVAL command, which works pretty well.
That enables access to all normal cache methods (put, get, add, remove, update...) with Twemproxy.

If Lua is not available though, `Update` will not be supported as Twemproxy doesn't allow the commands I'm using in no-script mode...

Also, I cannot determine the version of Redis running behind Twemproxy which makes it impossible to access the available features. So, in case someone has to use Redis 2.4 for example (which doesn't have Lua support), they can set a new property via configuration `StrictCompatibilityModeVersion` to restrict the compatibility mode to that version.

Overall I'm pretty happy with the implementation. 
Let me know what you think and happy testing ;)

**Comment by TMiNus** [comment]
@MichaCo Awesome commit :)  I have reviewed the commit and the code and I am very happy with the final result too, it seems pretty close to what I did back in the day, although my version was a little more hacky

You deserve a 🥇 Keep the good work!!. We can close this ticket. I will report any issues in a new ticket :)
