### ISSUE TITLE
Dynamic reconfiguration

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#58]
Right now if we configure two layers of cache (Runtime Caching and Redis -- for example). If the Redis layer goes down acting as a Backplane, CacheManager start throwing exceptions as it should do. I think it will be a nice feature if we can have some sort of failover mechanism in place for those cases

**Comment by TMiNus** [comment]
I have done further investigation and I have discovered another potential problem. Basically it comes down to guarantee the *sync between caches*. For example in the *Add* operation we first add the item to the lower cache e.g *Redis* but if the connection fails in the middle of that operation the item gets added but it cannot publish the message into the *Backplane* because *Redis* is not available thus no sync will occur for that item (if the connection is restored for the next *Add* operation,it can happen again, eventually the sync will be lost). I think the solution could be allowing dynamic configuration for the cache.

For example if the *Redis* part fails we could reuse the *SystemRuntimeCache* handle thus the cache will keep functioning out of sync until the *Redis* connection can be restored. The problem right now with this approach is that every *SystemRuntimeCache* gets a GUID attached and there is no clear way of reusing an active handle in a new *CacheManager*. The second approach will be some deregister function so we can remove any handle from a *CacheManager*. This will allow us to modify a two handle cache to function like one

I would gladly accept some feedback on these ideas

**Comment by MichaCo** [comment]
to be honest, I think it is pretty normal, that, in case Redis goes down, the state of multiple CacheManager instances (with a first level cache) might run out of sync at some point.

First of all, why would Redis go down? If you use a cluster or a good failover setup, this should actually never happen, or only very very rarely... 

I implemented the backplate feature with that in mind and not to make it 100% bullet proof, which is pretty much impossible.
Yeah you could store things in one instance and sync it later. But could cause corrupted state of a cache entry (think about counters for example).

So, in those scenarios, the best thing you can do is throwing exceptions and re-issue the request, if CacheManager really cannot handle it because of some environment issue...
If you rely on Redis and Redis goes down for longer than just a restart, your system is pretty much screwed anyways ;)

Does that make sense? ;)

**Comment by TMiNus** [comment]
I agree with you that it will be better to make the Redis backend bulletproof rather than the Backplane implementation on CacheManager but it has some appeal to me the idea of changing layers dynamically. When I was talking about just using one instance to store things I never intended to re-sync those items (eventually they will expire by themselves or they will be rewritten by the clients) once the Redis gets rolling again. Do you agree on the part of using an active layer to seed another CacheManager instance (in the same machine of course)?

**Comment by MichaCo** [comment]
> You mentioned counters, are you referring to the stats counters

No, I meant storing a counter/increment thing in Redis. If you increment a key, while Redis is down, and then try to sync them later from two or more instances, its impossible to figure out what the new/correct number might be...

Yeah sure, CacheManager could take another cache to copy over the values, although, what exactly would be the use case for that?

Maybe it would be easier to add an API to disable (and later enable) a cache layer, so that you can continue working if you want and you know what you are doing. And at some point you switch the distributed cache back on. The cache would work as if nothing has happend...
Although the local and distributed cache layer could be highly out of sync at that point...

I'm still not sure if that's really worth the effort implementing, considering the danger of what could happen if you somewhat rely on some kind of consistency?

Again, I'd like to hear if there is really a practical use case for those things ;)

**Comment by TMiNus** [comment]
I haven't gone into the implementation detail of the Update operation (I assume we are using this to increment the counter) but from the documentation I can remember that it is guaranteed that we will be working with the last version of the counter (don't know if this change would break something there). 

> If you increment a key, while Redis is down, and then try to sync them later from two or more instances

I never intent to sync the two layers when the connection to Redis gets restored. Eventually they will be in sync, either by expiration or rewriting from the client

> Yeah sure, CacheManager could take another cache to copy over the values

I don't want to copy the values. I intent to use the instance of the **localcache** that we already have into creating the new CacheManager instance (this would only work for RuntimeCaching and Dictionary)

> Maybe it would be easier to add an API to disable (and later enable) a cache layer

I agree with you that this will be the perfect solution, but I don't even know where to start to accomplish it. I suppose the **BaseCacheManager** class will be a good starting point. I think that creating a new CacheManager instance with an active **localcache** is an easier solution

In the matter of the uses cases, the only one I can think of right now is resilience against failures in the distributed cache layer. I think that the ability to dynamic reconfigure the cache will give the user a lot of flexibility in a lot of scenarios (maybe I am wrong :( ) .
