### ISSUE TITLE
Get all cached item keys

### ISSUE THREAD

**Issue by willdrob** [MichaCo/CacheManager#69]
Is it possible to get all the cached item keys? It would be helpful to know exactly what is cached at any point.

**Comment by MichaCo** [comment]
No it is not easily possible. Some cache systems do not support this in any way. 
In Redis for example, you'd have to run a `keys *` command, which is extremely expensive if you have a lot of keys and is explicitly not meant to be used in your business logic.
That's why CacheManager does not expose any of that.

That being said, if you need that functionality and only want an in-process cache, simply use a dictionary.

**Comment by MichaCo** [comment]
This feature is now in the works, feel free to engage into the conversation and design in #163

**Comment by indra444** [comment]
Is the implementation to get all cached item keys is done? If yes, it is available in which version?

**Comment by MichaCo** [comment]
No this is not done. There was some design and PR
