### ISSUE TITLE
Cache size and list of regions

### ISSUE THREAD

**Issue by kotynia** [MichaCo/CacheManager#70]
Hello, it is possible to get cache size and list of regions?. 
It would be very helpful for diagnostics and maintenance.

**Comment by MichaCo** [comment]
For cache size, you can iterate the cache handles and check the `Count`. There cannot be an accurate count across all cache handles because each can have a different value...
For Redis the count might also not be 100% accurate

And no, there is no list of regions, same as for list of all keys, this not something a cache usually has, feature wise. You'd have to track that information yourself if you want

**Comment by marcinKotynia** [comment]
Thank you, i think than 100% accuracy is not needed. I understand that there are many factors including expiration of items but in other hand simple information   
- region 
- **estimated** item count 
could be very helpful if it will be possible to consider at some point it would be great :)

**Comment by kotynia** [comment]
Cleanup
