### ISSUE TITLE
 sqldependcy support

### ISSUE THREAD

**Issue by niufwshd** [MichaCo/CacheManager#71]
first thank you for your good job and share，I have a question,Is It support sqldependcy in future,any answer would be appreciate。

**Comment by MichaCo** [comment]
I currently have no plans to implement dependency graphs in the near future. 
And no, sql deps is not a thing I'm interested in for now

**Comment by jzabroski** [comment]
You may have misunderstood the person's question. `SqlDependency` is a .NET
class that handles SQL Server Query Notifications to notify observers if an
underlying table changed. I don't fully understand the API and/or its
behavior, but the killer is that all subscriptions are non-durable and so
it was design for caching, and not for change notification. ASP.NET
implements a class called `SqlCacheDependency` that wraps this logic.

I think it's a terrible feature and have never seen it widely used.

https://msdn.microsoft.com/en-us/library/62xk7953(v=vs.110).aspx

On Jul 4, 2016 5:16 AM, "MichaC" <notifications@github.com> wrote:

I currently have no plans to implement dependency graphs in the near
future.
And no, sql deps is not a thing I'm interested in for now

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MichaCo/CacheManager/issues/71#issuecomment-230244414>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAbT_VD3vADFdVVUjZy5j8TSfer1EsAHks5qSM9rgaJpZM4JD4S7>
.

**Comment by MichaCo** [comment]
Yeah you are right. And no I never used it either and I have no plans to integrate it into this library in any way. I guess you can just use it somehow together anyways though and remove items from cache or so...
Don't really see how there is anything more to it I could do
