### ISSUE TITLE
Disposing Cache Expiration objects

### ISSUE THREAD

**Issue by AnguisCaptor** [MichaCo/CacheManager#73]
I was wondering if it would be possible to call "Dispose" on objects which are getting removed from cache
I couldn't find anything about this quickly

**Comment by MichaCo** [comment]
You mean CacheManager should call Dispose on an object which gets removed?
No that's not possible and also doesn't make a lot of sense

**Comment by AnguisCaptor** [comment]
does not make a lot of sense ? so in short we should leave in the memory leaks ?

**Comment by MichaCo** [comment]
No, I think you should just not cache objects which are disposable/complex which may keep references to stuff like a Stream... That's just a bad idea.

As long as you cache POCOs you do not have to do anything. GC will handle it at some point.

But to clarify why it is not possible. In some cache systems, I don't get any notification or callback when an item gets removed due to cache policies. So there is no way to tell when the item got removed.
