### ISSUE TITLE
Cache manager doesn't handle gracefully when Redis backplane connection goes down.

### ISSUE THREAD

**Issue by marto83** [MichaCo/CacheManager#78]
We've been using the CacheManager for a few months and it has been working great until we had an outage to Redis servers. This caused the whole website to go down. 

Here is out config:
```
  <cacheManager xmlns="http://tempuri.org/CacheManagerCfg.xsd">
    <managers>
      <cache name="inProcessCache" updateMode="Up" enableStatistics="true"   enablePerformanceCounters="true">
        <handle name="default" ref="runtimeHandle" />
      </cache>
      <cache name="redisWithBackPlane" enableStatistics="true" enablePerformanceCounters="true" backPlateName="redis" backPlateType="CacheManager.Redis.RedisCacheBackPlate, CacheManager.StackExchange.Redis">
        <handle name="default" ref="runtimeHandle" />
        <handle name="redis" ref="redisHandle" expirationMode="None" isBackPlateSource="true" />
      </cache>
    </managers>
    <cacheHandles>
      <handleDef  id="runtimeHandle"   type="CacheManager.SystemRuntimeCaching.MemoryCacheHandle`1, CacheManager.SystemRuntimeCaching" defaultExpirationMode="Sliding" defaultTimeout="5m"/>
      <handleDef  id="redisHandle"  type="CacheManager.Redis.RedisCacheHandle`1, CacheManager.StackExchange.Redis" defaultExpirationMode="Sliding" defaultTimeout="5m" />
    </cacheHandles>
  </cacheManager>
```

The desired behaviour will be to stop using the backplane until it comes back online. 
Here is the exact error message.

![image](https://cloud.githubusercontent.com/assets/150508/17308204/bed94e4e-5830-11e6-82d8-e574b2bb19d2.png)

**Comment by MichaCo** [comment]
The error does not come from the backplane. The error and stacktrace shows CacheManager tries to run a LUA script via EVAL, which is only the case if you try to Put, Add or Get (or similar) a value from Redis.

CacheManager has build in retry if Redis is down for a few seconds. After that period, it WILL throw an Exception.

That's the expected behavior!
You can tweak the retry count and timeout to eventually wait longer, but in case Redis is really gone, you have to handle that somehow in your application. That's not something CacheManager can completely handle for you ;)

That being said, a Redis Server which runs on multiple nodes with slaves etc, or a Cluster, should actually almost never fail.

**Comment by marto83** [comment]
Ok. Fair point. I'll add some exception handling for the rare case when this happens. 

Everything fails at some point. We are using Redis as a managed service and a whole datacentre lost connectivity so we went down as well.

**Comment by TMiNus** [comment]
Just a heads up. You can subscribe to the events from **ConnectionFailed** and **ConnectionRestored** from StackExchange.Redis, with that you can detect the connection going down and up (StackExchange.Redis handles this pretty well). You will need to tweak the RedisConnectionManager class a little :)
