### ISSUE TITLE
Redis cache performance question

### ISSUE THREAD

**Issue by tatarincev** [MichaCo/CacheManager#86]
Have you guys experienced performace issues with Redis over time. In other words the longer the cache is up and serving content the slower it gets. Almost seems like its not closing or sharing connections to the cache

**Comment by brianmrush** [comment]
Same question.  Saw this
http://stackoverflow.com/questions/25416562/stackexchange-redis-with-azure-redis-is-unusably-slow-or-throws-timeout-errors

**Comment by MichaCo** [comment]
Well, I can you say that if I run my tests, which does heavy compute per second all the time, I never encountered any change in performance and/or memory footprint of my application.
Depending on what you are doing, which version of redis, stackexchange.redis and where Redis is running, you results may vary a lot. 
So it is really hard to tell ^^

If you can provide numbers or code to reproduce your behavior, that would help a lot to figure out what's going on... Otherwise, I think I cannot really help you with that ;)

**Comment by MichaCo** [comment]
@tatarincev 
closing this as it is unclear if that has anything todo with CacheManager
