### ISSUE TITLE
Invalidating multiple regions

### ISSUE THREAD

**Issue by VahidN** [MichaCo/CacheManager#92]
Suppose we have two entities: Blogs and Posts
Cached query-1 fetches the Posts list. Region: Posts
Cached query-2 fetches Posts and Blogs Titles. Region: Posts and Blogs

Now we add a new Post. All of the above cached items should be invalidated (Posts is common between them).
How can I define the region of the query-2 correctly? Or How can I invalidate it when a new post is added?

With `System.Web.Caching` it's possible to add two `rootCacheKey`s for Blogs and Posts:
```
cache.Add(
	rootCacheKey1,
	rootCacheKey1,
	null,
	System.Web.Caching.Cache.NoAbsoluteExpiration,
	System.Web.Caching.Cache.NoSlidingExpiration,
	CacheItemPriority.Default,
	RootCacheItemRemoved);

cache.Add(
	rootCacheKey2,
	rootCacheKey2,
	null,
	System.Web.Caching.Cache.NoAbsoluteExpiration,
	System.Web.Caching.Cache.NoSlidingExpiration,
	CacheItemPriority.Default,
	RootCacheItemRemoved);
```

And then create a `CacheDependency`, based on an array of `rootCacheKey`s:
```
cache.Add(
				cacheKey,
				new DictionaryEntry(key, value),
				new CacheDependency(null, new[] {rootCacheKey1, rootCacheKey2}),
				DateTime.Now.Add(expiration),
				System.Web.Caching.Cache.NoSlidingExpiration,
				priority,
				null);
```
By removing `rootCacheKey1` the dependent caches would be invalidated, for the combination of `new[] {rootCacheKey1, rootCacheKey2}` or `new[] {rootCacheKey1}`.

Is it possible to do the same thing here?

**Comment by MichaCo** [comment]
First of all, no, CacheManager currently doesn't support defining cache dependencies for various reasons; main reason is, that only some cache systems support that mechanic. 
Redis for example doesn't. If I have a dependency on a cache item which gets evicted by expiration in Redis, the only way to do so would be manually by listening on key space events, a feature which is not enabled per default and disabled on Azure for example. Other distributed caches like Memcached doesn't have any of that.

Regarding your case, to be honest, I don't really get what the problem is. If you always delete everything anyways, just store your blog posts in a region and the titles on one key or a different region. If you have to clear both, just call ClearRegion or Remove(key) on both of those manually. I don't see why you'd need cache dependencies at all

**Comment by VahidN** [comment]
Thanks for the reply. I need cache dependencies because of different variations of the query-1 and 2. There are hundreds of queries here with different keys, but they are dependent on these two entities (and also the system has other entities/queries too). I want to invalidate the related queries easily, when one of the entities has changed.

**Comment by TMiNus** [comment]
This was already discussed in #31, I proposed some ideas there. The way I implemented it was creating the dependency tree in the cache itself, similar to how the regions are implemented. In that way every cache could have dependencies.

FYI when I was thinking on how to implement dependencies I also started to look at regions but after a while I realized it was not enough, you actually need to create the dependency tree into the cache itself
