### ISSUE TITLE
Guidelines on local thread synchronization and async/await?

### ISSUE THREAD

**Issue by sam-piper** [MichaCo/CacheManager#96]
Hi, I'm looking for some guidance on thread safety and using async/await with the ICacheManager interface, I couldn't find any explicit mention of this topic in the existing docs.

These are my specific questions:

- Are all ICacheManager methods considered thread-safe for local threads? Do I need to lock access to any methods such as Add(), Put(), GetOrAdd(), or are they all atomic? Obviously if I call multiple methods in sequence I will need a lock around them, but just wanted to check if it was required for single calls.

- There is no use of async / await in the existing ICacheManager API, so from that can I assume that any ICacheManager calls are always synchronous for the executing thread, even if there are additional calls to a Redis backplane, etc.? I'm considering layering an async/await API on top of ICacheManager.

Thanks for the help.

**Comment by MichaCo** [comment]
This has been answered in some issues already.
Again, all cache handles / methods are thread safe. 
Thread-safe just means that you'll never get concurrent modification exceptions or similar, for example. It does not mean that all methods are atomic.

Add is kind of atomic as you will not be able to call Add for the same key on two threads. Only one will win, the other one will return false. That's why GetOrAdd might loop 1-2 times in those situations.

Put will always execute. If two threads run `Put` on the same key at the same time, one of them will override the other's changes. 
If you don't want that behavior, use the `Update` method, which ensures that you run the update code on the most recent version. If many threads try to `Update` the same key, the update command might be re-run several times with the "new version" of the stored value.

In case of Redis, `Put` will also be run with fire and forget, which is kind of async (implemented by the StackExchange.Redis client, see #89).
`Add` is always synchronous because we have to check if the operation was successful or, in case the key was already stored in the cache, we have to return `false`.

So, no, you do not need to add locks around any of those calls at all. 
A lock on your current thread doesn't help you with distributed caches and multiple clients connected anyways, right? So in most scenarios, lock doesn't make sense.

As mentioned in #89, async/await didn't make much sense for CacheManager. 
In-memory caches do not have any async IO or networking at all, and usually you always have an in-memory cache layer configured, meaning, it doesn't really help much

You also mentioned the backplane, the Pub/Sub stuff and the whole implementation is running on a separated task (message pooling etc...). So that's totally async for example.

**Comment by sam-piper** [comment]
Thanks for the info, that's very helpful - particularly the finer points on Put.
