### ISSUE TITLE
Setting the Logger from App/Web config

### ISSUE THREAD

**Issue by TMiNus** [MichaCo/CacheManager#98]
I have been digging around the logging portion of the project and I think there is no way of setting the logger in the App/Web config file.

Right now the only way of setting the logger without using the Microsoft.Extension.Configuration is to configure the cache by hand and then add the logger there with the `WithLogging` method 

I think the process should be similar to the Serializer configuration

**Comment by MichaCo** [comment]
Reason here is that I didn't want to add configuration sections and all that kind of stuff for the new Microsoft extension packages. 
The way of configuring logging and DI and all that in the new dotnet core way is more code focused, with custom json configurations eventually. 
I didn't really see the need to add options for the "old" web/app config way...
Also, it will be pretty tricky to configure it because of the different providers. At some point, the logger factory has to be constructed and log providers have to be added. Would be a lot of code to do that all via configuration...

The json configuration allows you to select a logger factory type. 
That being said, it does not support log level or anything else right now (same reasons as above).

I think a good way to work around this missing part is to combine the configuration via files with some custom code which defines the logging part only, for example:

``` CSharp
// load MS configuration and add a json file defining the cache manager configuration
var configBuilder = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
    .AddJsonFile("cache.json");

// get the cache configuration from the ms configuration stuff
var configuration = configBuilder.Build()
    .GetCacheConfiguration()
    .Builder  // access the builder
    .WithMicrosoftLogging(l => l.AddConsole(LogLevel.Debug))  // define logging
    .Build();  // return the new configuation

// or get the configuration from web/app.config and do the same thing
var configuration2 = CacheManager.Core.ConfigurationBuilder.LoadConfiguration("section", "configName")
    .Builder
    .WithMicrosoftLogging(l => l.AddConsole(LogLevel.Debug))
    .Build();

// then new up the cache manager or add the configuration to your DI
var aCache = new BaseCacheManager<string>(configuration);

```

**Comment by TMiNus** [comment]
Thanks for the response. I do agree that your way is cleaner.

I already tried it with my NLog adapter and it works flawlessly :)
